#lang sicp

(define (make-account balance secret-password)
  (define times 0)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (pass-prompt amount)
    "Incorrect password")
  (define (call-the-cops amount)
    "You have made 5 consecutive incorrect trys. This incident will be reported to the cops. Contact the bank for more details.")
  (define (dispatch input-password m)
    (if (eq? input-password secret-password)
        (begin (set! times 0) (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request: MAKE-ACCOUNT"
                           m))) )
        (begin (set! times (+ times 1)) (if (> times 5) call-the-cops pass-prompt))))
  dispatch)

;(define acc (make-account 100 'pass123))
;((acc 'pass123 'withdraw) 40)
;((acc 'pass123 'deposit) 50)
;((acc 'pass123 'withdraw) 50)
;((acc 'pass123 'withdraw) 500)
;((acc 'pass321 'withdraw) 50)
;((acc 'pass321 'withdraw) 50)
;((acc 'pass321 'withdraw) 50)
;((acc 'pass321 'withdraw) 50)
;((acc 'pass321 'withdraw) 50)
;((acc 'pass123 'withdraw) 40)
;((acc 'pass321 'withdraw) 50)